% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother





\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{booktabs}
\usepackage{caption}
\usepackage{longtable}
\usepackage{colortbl}
\usepackage{array}
\usepackage{anyfontsize}
\usepackage{multirow}
\usepackage{fontspec}
\usepackage{multicol}
\usepackage{ulem}
\usepackage{hhline}
\newlength\Oldarrayrulewidth
\newlength\Oldtabcolsep
\usepackage{hyperref}
\usepackage{float}
\usepackage{wrapfig}
\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Session 2: PCOS and Inflammatory Markers in Menstrual Cycle},
  pdfauthor={Data Science for Biology Workshop},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Session 2: PCOS and Inflammatory Markers in Menstrual Cycle}
\author{Data Science for Biology Workshop}
\date{}
\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\setcounter{tocdepth}{3}
\tableofcontents
}

\subsection{Research Question}\label{research-question}

\begin{quote}
\textbf{Do inflammatory marker levels differ between participants with
PCOS and participants without PCOS after accounting for menstrual-cycle
stage?}
\end{quote}

In this analysis we compare inflammatory cytokine concentrations between
participants diagnosed with PCOS and those with no disease, while
adjusting for the time point (menstrual-cycle stage) as a covariate.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Data Import}\label{data-import}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ============================================================================}
\CommentTok{\# Read all CSV files from the dataset directory}
\CommentTok{\# ============================================================================}

\CommentTok{\# Participant metadata: age, PCOS status, arm, period product, sex}
\NormalTok{participant\_meta }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"data/group\_b\_menstruation/01\_participant\_metadata\_period.csv"}\NormalTok{,}
                             \AttributeTok{show\_col\_types =} \ConstantTok{FALSE}\NormalTok{)}

\CommentTok{\# Sample IDs mapping: links participants to their samples across time points}
\NormalTok{sample\_ids }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"data/group\_b\_menstruation/00\_sample\_ids\_period.csv"}\NormalTok{,}
                       \AttributeTok{show\_col\_types =} \ConstantTok{FALSE}\NormalTok{)}

\CommentTok{\# Luminex cytokine concentrations}
\NormalTok{luminex }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"data/group\_b\_menstruation/02\_luminex\_period.csv"}\NormalTok{,}
                    \AttributeTok{show\_col\_types =} \ConstantTok{FALSE}\NormalTok{)}

\CommentTok{\# Preview each dataset}
\FunctionTok{glimpse}\NormalTok{(participant\_meta)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Rows: 27
Columns: 6
$ pid            <chr> "pid_01", "pid_02", "pid_03", "pid_04", "pid_05", "pid_~
$ arm            <chr> "birth_control", "birth_control", "no_birth_control", "~
$ age            <dbl> 34, 30, 29, 31, 30, 41, 30, 30, 30, 27, 35, 30, 29, 30,~
$ pcos_status    <chr> "no disease", "pcos", "pcos", "pcos", "pcos", "pcos", "~
$ period_product <chr> "tampon", "menstrual_cup", "tampon", "pad", "tampon", "~
$ sex            <chr> "female", "female", "female", "female", "female", "fema~
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{glimpse}\NormalTok{(sample\_ids)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Rows: 108
Columns: 4
$ pid        <chr> "pid_12", "pid_04", "pid_26", "pid_08", "pid_16", "pid_27",~
$ time_point <chr> "week_post", "week_post", "onset", "end_bleeding", "week_po~
$ arm        <chr> "birth_control", "birth_control", "birth_control", "no_birt~
$ sample_id  <chr> "SAMP001", "SAMP002", "SAMP003", "SAMP004", "SAMP005", "SAM~
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{glimpse}\NormalTok{(luminex)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Rows: 864
Columns: 4
$ sample_id <chr> "SAMP048", "SAMP048", "SAMP048", "SAMP048", "SAMP048", "SAMP~
$ cytokine  <chr> "IL-1a", "IL-1b", "IL-6", "TNFa", "MIG", "IFNg", "IP-10", "M~
$ conc      <dbl> 0.75898551, 1.98212496, 0.09155273, 0.21362305, 180.45283113~
$ limits    <chr> "not_censored", "not_censored", "below_detection_limit", "be~
\end{verbatim}

\subsection{Data Validation}\label{data-validation}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ============================================================================}
\CommentTok{\# Validate key identifiers and merge datasets}
\CommentTok{\# ============================================================================}

\CommentTok{\# {-}{-}{-} Participant metadata checks {-}{-}{-}}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Number of participants:"}\NormalTok{, }\FunctionTok{n\_distinct}\NormalTok{(participant\_meta}\SpecialCharTok{$}\NormalTok{pid), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Number of participants: 27 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"PCOS status levels:"}\NormalTok{, }\FunctionTok{unique}\NormalTok{(participant\_meta}\SpecialCharTok{$}\NormalTok{pcos\_status), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
PCOS status levels: no disease pcos 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Sex levels:"}\NormalTok{, }\FunctionTok{unique}\NormalTok{(participant\_meta}\SpecialCharTok{$}\NormalTok{sex), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Sex levels: female 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Arms:"}\NormalTok{, }\FunctionTok{unique}\NormalTok{(participant\_meta}\SpecialCharTok{$}\NormalTok{arm), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Arms: birth_control no_birth_control 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Period products:"}\NormalTok{, }\FunctionTok{unique}\NormalTok{(participant\_meta}\SpecialCharTok{$}\NormalTok{period\_product), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Period products: tampon menstrual_cup pad 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}{-}{-} Sample ID checks {-}{-}{-}}
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Number of samples:"}\NormalTok{, }\FunctionTok{n\_distinct}\NormalTok{(sample\_ids}\SpecialCharTok{$}\NormalTok{sample\_id), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Number of samples: 108 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Time points:"}\NormalTok{, }\FunctionTok{unique}\NormalTok{(sample\_ids}\SpecialCharTok{$}\NormalTok{time\_point), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Time points: week_post onset end_bleeding week_prior 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Unique PIDs in sample\_ids:"}\NormalTok{, }\FunctionTok{n\_distinct}\NormalTok{(sample\_ids}\SpecialCharTok{$}\NormalTok{pid), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Unique PIDs in sample_ids: 27 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check that all PIDs in sample\_ids exist in participant\_meta}
\NormalTok{pid\_in\_both }\OtherTok{\textless{}{-}} \FunctionTok{all}\NormalTok{(sample\_ids}\SpecialCharTok{$}\NormalTok{pid }\SpecialCharTok{\%in\%}\NormalTok{ participant\_meta}\SpecialCharTok{$}\NormalTok{pid)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{All sample PIDs found in participant metadata:"}\NormalTok{, pid\_in\_both, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

All sample PIDs found in participant metadata: TRUE 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}{-}{-} Luminex checks {-}{-}{-}}
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Unique cytokines:"}\NormalTok{, }\FunctionTok{unique}\NormalTok{(luminex}\SpecialCharTok{$}\NormalTok{cytokine), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Unique cytokines: IL-1a IL-1b IL-6 TNFa MIG IFNg IP-10 MIP-3a 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Number of cytokines:"}\NormalTok{, }\FunctionTok{n\_distinct}\NormalTok{(luminex}\SpecialCharTok{$}\NormalTok{cytokine), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Number of cytokines: 8 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Unique sample IDs in luminex:"}\NormalTok{, }\FunctionTok{n\_distinct}\NormalTok{(luminex}\SpecialCharTok{$}\NormalTok{sample\_id), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Unique sample IDs in luminex: 108 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check that all luminex sample IDs exist in sample\_ids}
\NormalTok{sample\_in\_both }\OtherTok{\textless{}{-}} \FunctionTok{all}\NormalTok{(luminex}\SpecialCharTok{$}\NormalTok{sample\_id }\SpecialCharTok{\%in\%}\NormalTok{ sample\_ids}\SpecialCharTok{$}\NormalTok{sample\_id)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"All luminex sample IDs found in sample\_ids:"}\NormalTok{, sample\_in\_both, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
All luminex sample IDs found in sample_ids: TRUE 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}{-}{-} Merge into analysis dataset {-}{-}{-}}
\CommentTok{\# Step 1: Join sample\_ids with participant\_meta}
\CommentTok{\# Both datasets have \textquotesingle{}arm\textquotesingle{}, so we keep it from participant\_meta}
\NormalTok{analysis\_data }\OtherTok{\textless{}{-}}\NormalTok{ sample\_ids }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{left\_join}\NormalTok{(participant\_meta, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"pid"}\NormalTok{, }\StringTok{"arm"}\NormalTok{))}

\CommentTok{\# Step 2: Join with luminex}
\NormalTok{analysis\_data }\OtherTok{\textless{}{-}}\NormalTok{ analysis\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{left\_join}\NormalTok{(luminex, }\AttributeTok{by =} \StringTok{"sample\_id"}\NormalTok{)}

\CommentTok{\# Step 3: Create log{-}transformed concentration}
\CommentTok{\# log1p = log(1 + x) handles zeros gracefully}
\NormalTok{analysis\_data }\OtherTok{\textless{}{-}}\NormalTok{ analysis\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{log\_conc =} \FunctionTok{log1p}\NormalTok{(conc))}

\CommentTok{\# Final dataset: select the columns we need}
\NormalTok{analysis\_data }\OtherTok{\textless{}{-}}\NormalTok{ analysis\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(pid, pcos\_status, age, arm, period\_product, time\_point,}
\NormalTok{         cytokine, conc, log\_conc)}

\CommentTok{\# Remove any rows with missing cytokines (no luminex measurement)}
\NormalTok{analysis\_data }\OtherTok{\textless{}{-}}\NormalTok{ analysis\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(cytokine))}

\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Final analysis dataset dimensions:"}\NormalTok{, }\FunctionTok{dim}\NormalTok{(analysis\_data), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Final analysis dataset dimensions: 864 9 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Number of participants:"}\NormalTok{, }\FunctionTok{n\_distinct}\NormalTok{(analysis\_data}\SpecialCharTok{$}\NormalTok{pid), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Number of participants: 27 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Number of observations:"}\NormalTok{, }\FunctionTok{nrow}\NormalTok{(analysis\_data), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Number of observations: 864 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{glimpse}\NormalTok{(analysis\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Rows: 864
Columns: 9
$ pid            <chr> "pid_12", "pid_12", "pid_12", "pid_12", "pid_12", "pid_~
$ pcos_status    <chr> "no disease", "no disease", "no disease", "no disease",~
$ age            <dbl> 30, 30, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31,~
$ arm            <chr> "birth_control", "birth_control", "birth_control", "bir~
$ period_product <chr> "tampon", "tampon", "tampon", "tampon", "tampon", "tamp~
$ time_point     <chr> "week_post", "week_post", "week_post", "week_post", "we~
$ cytokine       <chr> "IL-1a", "IL-1b", "IL-6", "TNFa", "MIG", "IFNg", "IP-10~
$ conc           <dbl> 9.42421205, 0.88900255, 0.09155273, 0.21362305, 89.6939~
$ log_conc       <dbl> 2.34413118, 0.63604894, 0.08760121, 0.19361014, 4.50749~
\end{verbatim}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Table 1: Participant Characteristics by PCOS
Status}\label{table-1-participant-characteristics-by-pcos-status}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ============================================================================}
\CommentTok{\# Create Table 1 using gtsummary, grouped by pcos\_status}
\CommentTok{\# ============================================================================}

\CommentTok{\# Use distinct participant{-}level data (one row per participant)}
\NormalTok{participant\_tbl }\OtherTok{\textless{}{-}}\NormalTok{ participant\_meta }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{distinct}\NormalTok{(pid, }\AttributeTok{.keep\_all =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Remove \textquotesingle{}sex\textquotesingle{} if it has only one level — it does (all "female")}
\NormalTok{sex\_levels }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(participant\_tbl}\SpecialCharTok{$}\NormalTok{sex)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Sex levels:"}\NormalTok{, sex\_levels, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Sex levels: female 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Build Table 1}
\NormalTok{tbl1 }\OtherTok{\textless{}{-}}\NormalTok{ participant\_tbl }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(pcos\_status, age, arm, period\_product) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{tbl\_summary}\NormalTok{(}
    \AttributeTok{by =}\NormalTok{ pcos\_status,}
    \AttributeTok{label =} \FunctionTok{list}\NormalTok{(}
\NormalTok{      age }\SpecialCharTok{\textasciitilde{}} \StringTok{"Age (years)"}\NormalTok{,}
\NormalTok{      arm }\SpecialCharTok{\textasciitilde{}} \StringTok{"Birth control use"}\NormalTok{,}
\NormalTok{      period\_product }\SpecialCharTok{\textasciitilde{}} \StringTok{"Period product"}
\NormalTok{    ),}
    \AttributeTok{statistic =} \FunctionTok{list}\NormalTok{(}
      \FunctionTok{all\_continuous}\NormalTok{() }\SpecialCharTok{\textasciitilde{}} \StringTok{"\{mean\} (\{sd\})"}\NormalTok{,}
      \FunctionTok{all\_categorical}\NormalTok{() }\SpecialCharTok{\textasciitilde{}} \StringTok{"\{n\} (\{p\}\%)"}
\NormalTok{    ),}
    \AttributeTok{digits =} \FunctionTok{list}\NormalTok{(age }\SpecialCharTok{\textasciitilde{}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{add\_p}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{add\_overall}\NormalTok{()}

\CommentTok{\# Display in document}
\NormalTok{tbl1}
\end{Highlighting}
\end{Shaded}

\begin{table}
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lcccc}
\toprule
\textbf{Characteristic} & \textbf{Overall}  N = 27\textsuperscript{\textit{1}} & \textbf{no disease}  N = 13\textsuperscript{\textit{1}} & \textbf{pcos}  N = 14\textsuperscript{\textit{1}} & \textbf{p-value}\textsuperscript{\textit{2}} \\ 
\midrule\addlinespace[2.5pt]
Age (years) & 31.4 (2.9) & 30.5 (2.5) & 32.1 (3.1) & 0.2 \\ 
Birth control use &  &  &  & 0.2 \\ 
    birth\_control & 15 (56\%) & 9 (69\%) & 6 (43\%) &  \\ 
    no\_birth\_control & 12 (44\%) & 4 (31\%) & 8 (57\%) &  \\ 
Period product &  &  &  & 0.2 \\ 
    menstrual\_cup & 4 (15\%) & 2 (15\%) & 2 (14\%) &  \\ 
    pad & 4 (15\%) & 0 (0\%) & 4 (29\%) &  \\ 
    tampon & 19 (70\%) & 11 (85\%) & 8 (57\%) &  \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\vspace{.05em}
\textsuperscript{\textit{1}}Mean (SD); n (\%)\\
\textsuperscript{\textit{2}}Wilcoxon rank sum test; Pearson's Chi-squared test; Fisher's exact test\\
\end{minipage}
\end{table}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Export to HTML}
\NormalTok{tbl1 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{as\_flex\_table}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  flextable}\SpecialCharTok{::}\FunctionTok{save\_as\_html}\NormalTok{(}\AttributeTok{path =} \StringTok{"Table\_1\_PCOS\_vs\_NoDisease.html"}\NormalTok{)}

\CommentTok{\# Export to Word}
\NormalTok{tbl1 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{as\_flex\_table}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  flextable}\SpecialCharTok{::}\FunctionTok{save\_as\_docx}\NormalTok{(}\AttributeTok{path =} \StringTok{"Table\_1\_PCOS\_vs\_NoDisease.docx"}\NormalTok{)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Table 1 saved to Table\_1\_PCOS\_vs\_NoDisease.html and .docx}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Table 1 saved to Table_1_PCOS_vs_NoDisease.html and .docx
\end{verbatim}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Cytokine Comparison
Figure}\label{cytokine-comparison-figure}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ============================================================================}
\CommentTok{\# Boxplots of log{-}transformed cytokine concentrations by PCOS status}
\CommentTok{\# ============================================================================}

\CommentTok{\# Detect cytokines dynamically from the data}
\NormalTok{cytokines }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(analysis\_data}\SpecialCharTok{$}\NormalTok{cytokine)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Cytokines detected:"}\NormalTok{, }\FunctionTok{paste}\NormalTok{(cytokines, }\AttributeTok{collapse =} \StringTok{", "}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Cytokines detected: IL-1a, IL-1b, IL-6, TNFa, MIG, IFNg, IP-10, MIP-3a 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create the boxplot}
\NormalTok{p }\OtherTok{\textless{}{-}}\NormalTok{ analysis\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggboxplot}\NormalTok{(}\AttributeTok{x =} \StringTok{"pcos\_status"}\NormalTok{, }\AttributeTok{y =} \StringTok{"log\_conc"}\NormalTok{,}
            \AttributeTok{color =} \StringTok{"pcos\_status"}\NormalTok{,}
            \AttributeTok{palette =} \FunctionTok{c}\NormalTok{(}\StringTok{"\#E69F00"}\NormalTok{, }\StringTok{"\#56B4E9"}\NormalTok{),}
            \AttributeTok{add =} \StringTok{"jitter"}\NormalTok{,}
            \AttributeTok{add.params =} \FunctionTok{list}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.4}\NormalTok{, }\AttributeTok{size =} \FloatTok{1.2}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{stat\_compare\_means}\NormalTok{(}\AttributeTok{method =} \StringTok{"wilcox.test"}\NormalTok{,}
                     \AttributeTok{label =} \StringTok{"p.signif"}\NormalTok{,}
                     \AttributeTok{hide.ns =} \ConstantTok{FALSE}\NormalTok{,}
                     \AttributeTok{size =} \FloatTok{3.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ cytokine, }\AttributeTok{scales =} \StringTok{"free\_y"}\NormalTok{, }\AttributeTok{ncol =} \DecValTok{4}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Inflammatory marker levels in PCOS and non{-}PCOS participants"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"PCOS Status"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"log(1 + concentration)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}
    \AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{face =} \StringTok{"bold"}\NormalTok{, }\AttributeTok{size =} \DecValTok{14}\NormalTok{),}
    \AttributeTok{strip.text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{face =} \StringTok{"bold"}\NormalTok{, }\AttributeTok{size =} \DecValTok{11}\NormalTok{),}
    \AttributeTok{legend.position =} \StringTok{"bottom"}
\NormalTok{  )}

\FunctionTok{print}\NormalTok{(p)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{session2_pcos_inflammatory_markers_files/figure-pdf/cytokine-figure-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Save as PNG}
\FunctionTok{ggsave}\NormalTok{(}\StringTok{"Figure\_1\_Cytokine\_Comparison.png"}\NormalTok{, }\AttributeTok{plot =}\NormalTok{ p,}
       \AttributeTok{width =} \DecValTok{12}\NormalTok{, }\AttributeTok{height =} \DecValTok{10}\NormalTok{, }\AttributeTok{dpi =} \DecValTok{300}\NormalTok{)}

\CommentTok{\# Save as PDF}
\FunctionTok{ggsave}\NormalTok{(}\StringTok{"Figure\_1\_Cytokine\_Comparison.pdf"}\NormalTok{, }\AttributeTok{plot =}\NormalTok{ p,}
       \AttributeTok{width =} \DecValTok{12}\NormalTok{, }\AttributeTok{height =} \DecValTok{10}\NormalTok{)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Figure saved to Figure\_1\_Cytokine\_Comparison.png and .pdf}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Figure saved to Figure_1_Cytokine_Comparison.png and .pdf
\end{verbatim}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Mixed-Effects Model}\label{mixed-effects-model}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ============================================================================}
\CommentTok{\# Fit a linear mixed{-}effects model for each cytokine}
\CommentTok{\# Formula: log\_conc \textasciitilde{} pcos\_status + time\_point + (1 | pid)}
\CommentTok{\#   {-} pcos\_status: fixed effect of interest (PCOS vs no disease)}
\CommentTok{\#   {-} time\_point: adjustment for menstrual{-}cycle stage}
\CommentTok{\#   {-} (1 | pid): random intercept per participant (accounts for repeated measures)}
\CommentTok{\# ============================================================================}

\CommentTok{\# Get unique cytokines}
\NormalTok{cytokines }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(analysis\_data}\SpecialCharTok{$}\NormalTok{cytokine)}

\CommentTok{\# Create a results dataframe}
\NormalTok{model\_results }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{()}

\ControlFlowTok{for}\NormalTok{ (cyt }\ControlFlowTok{in}\NormalTok{ cytokines) \{}
  \CommentTok{\# Subset data for this cytokine}
\NormalTok{  sub\_data }\OtherTok{\textless{}{-}}\NormalTok{ analysis\_data }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(cytokine }\SpecialCharTok{==}\NormalTok{ cyt) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}
      \CommentTok{\# Ensure pcos\_status is a factor with "no disease" as reference}
      \AttributeTok{pcos\_status =} \FunctionTok{factor}\NormalTok{(pcos\_status, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"no disease"}\NormalTok{, }\StringTok{"pcos"}\NormalTok{)),}
      \CommentTok{\# Ensure time\_point is a factor for the model}
      \AttributeTok{time\_point =} \FunctionTok{factor}\NormalTok{(time\_point, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"week\_prior"}\NormalTok{, }\StringTok{"onset"}\NormalTok{,}
                                                  \StringTok{"end\_bleeding"}\NormalTok{, }\StringTok{"week\_post"}\NormalTok{))}
\NormalTok{    )}

  \CommentTok{\# Fit the mixed{-}effects model}
  \CommentTok{\# Using lmerTest which provides p{-}values via Satterthwaite approximation}
\NormalTok{  fit }\OtherTok{\textless{}{-}} \FunctionTok{lmer}\NormalTok{(log\_conc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pcos\_status }\SpecialCharTok{+}\NormalTok{ time\_point }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ pid),}
              \AttributeTok{data =}\NormalTok{ sub\_data)}

  \CommentTok{\# Extract the coefficient for pcos\_status (PCOS vs no disease)}
\NormalTok{  coef\_summary }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(fit)}\SpecialCharTok{$}\NormalTok{coefficients}

  \CommentTok{\# Find the row for pcos\_status (it will be "pcos\_statuspcos")}
\NormalTok{  pcos\_row }\OtherTok{\textless{}{-}} \FunctionTok{grep}\NormalTok{(}\StringTok{"pcos\_status"}\NormalTok{, }\FunctionTok{rownames}\NormalTok{(coef\_summary))}

  \CommentTok{\# Get confidence interval}
\NormalTok{  ci }\OtherTok{\textless{}{-}} \FunctionTok{confint}\NormalTok{(fit, }\AttributeTok{parm =} \StringTok{"pcos\_statuspcos"}\NormalTok{, }\AttributeTok{method =} \StringTok{"Wald"}\NormalTok{)}

  \CommentTok{\# Store results}
\NormalTok{  row\_result }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
    \AttributeTok{cytokine =}\NormalTok{ cyt,}
    \AttributeTok{estimate =}\NormalTok{ coef\_summary[pcos\_row, }\StringTok{"Estimate"}\NormalTok{],}
    \AttributeTok{std\_error =}\NormalTok{ coef\_summary[pcos\_row, }\StringTok{"Std. Error"}\NormalTok{],}
    \AttributeTok{ci\_lower =}\NormalTok{ ci[}\DecValTok{1}\NormalTok{],}
    \AttributeTok{ci\_upper =}\NormalTok{ ci[}\DecValTok{2}\NormalTok{],}
    \AttributeTok{p\_value =}\NormalTok{ coef\_summary[pcos\_row, }\StringTok{"Pr(\textgreater{}|t|)"}\NormalTok{],}
    \AttributeTok{n\_obs =} \FunctionTok{nrow}\NormalTok{(sub\_data),}
    \AttributeTok{n\_participants =} \FunctionTok{n\_distinct}\NormalTok{(sub\_data}\SpecialCharTok{$}\NormalTok{pid),}
    \AttributeTok{stringsAsFactors =} \ConstantTok{FALSE}
\NormalTok{  )}

\NormalTok{  model\_results }\OtherTok{\textless{}{-}} \FunctionTok{rbind}\NormalTok{(model\_results, row\_result)}
\NormalTok{\}}

\CommentTok{\# Apply Benjamini{-}Hochberg correction across all cytokines}
\NormalTok{model\_results}\SpecialCharTok{$}\NormalTok{p\_adjusted }\OtherTok{\textless{}{-}} \FunctionTok{p.adjust}\NormalTok{(model\_results}\SpecialCharTok{$}\NormalTok{p\_value, }\AttributeTok{method =} \StringTok{"BH"}\NormalTok{)}

\CommentTok{\# Sort by adjusted p{-}value}
\NormalTok{model\_results }\OtherTok{\textless{}{-}}\NormalTok{ model\_results }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(p\_adjusted)}

\CommentTok{\# Display results}
\FunctionTok{kable}\NormalTok{(model\_results, }\AttributeTok{digits =} \DecValTok{4}\NormalTok{,}
      \AttributeTok{caption =} \StringTok{"Mixed{-}effects model results: PCOS effect on log cytokine concentration"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1047}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1047}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1163}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1047}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1047}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0930}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0698}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1744}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1279}}@{}}
\caption{Mixed-effects model results: PCOS effect on log cytokine
concentration}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
cytokine
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
estimate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
std\_error
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
ci\_lower
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
ci\_upper
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p\_value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_obs
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_participants
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p\_adjusted
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
cytokine
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
estimate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
std\_error
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
ci\_lower
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
ci\_upper
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p\_value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_obs
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_participants
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p\_adjusted
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
TNFa & 0.3484 & 0.1738 & 0.0079 & 0.6890 & 0.0559 & 108 & 27 & 0.3321 \\
IFNg & 0.2266 & 0.1255 & -0.0194 & 0.4725 & 0.0830 & 108 & 27 &
0.3321 \\
IL-1b & 0.3824 & 0.2609 & -0.1291 & 0.8938 & 0.1459 & 108 & 27 &
0.3890 \\
IL-1a & 0.0701 & 0.2821 & -0.4828 & 0.6230 & 0.8058 & 108 & 27 &
0.8058 \\
IL-6 & -0.0691 & 0.2099 & -0.4804 & 0.3423 & 0.7448 & 108 & 27 &
0.8058 \\
MIG & 0.1900 & 0.2966 & -0.3913 & 0.7713 & 0.5276 & 108 & 27 & 0.8058 \\
IP-10 & -0.2034 & 0.2468 & -0.6871 & 0.2803 & 0.4118 & 108 & 27 &
0.8058 \\
MIP-3a & -0.0780 & 0.1617 & -0.3949 & 0.2390 & 0.6308 & 108 & 27 &
0.8058 \\
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Write to CSV}
\FunctionTok{write\_csv}\NormalTok{(model\_results, }\StringTok{"Model\_Results\_PCOS\_Cytokines.csv"}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Model results saved to Model\_Results\_PCOS\_Cytokines.csv}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Model results saved to Model_Results_PCOS_Cytokines.csv
\end{verbatim}

\subsection{Model Results Summary}\label{model-results-summary}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ============================================================================}
\CommentTok{\# Highlight which cytokines are significant after BH correction}
\CommentTok{\# ============================================================================}

\FunctionTok{cat}\NormalTok{(}\StringTok{"=== Cytokines with significant PCOS effect (BH{-}adjusted p \textless{} 0.05) ===}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
=== Cytokines with significant PCOS effect (BH-adjusted p < 0.05) ===
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{significant }\OtherTok{\textless{}{-}}\NormalTok{ model\_results }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(p\_adjusted }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{nrow}\NormalTok{(significant) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
  \FunctionTok{print}\NormalTok{(significant }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(cytokine, estimate, p\_value, p\_adjusted))}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"No cytokines reached statistical significance after BH correction.}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
No cytokines reached statistical significance after BH correction.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{=== All cytokines ranked by adjusted p{-}value ===}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

=== All cytokines ranked by adjusted p-value ===
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(model\_results }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(cytokine, estimate, ci\_lower, ci\_upper, p\_value, p\_adjusted))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  cytokine    estimate     ci_lower  ci_upper    p_value p_adjusted
1     TNFa  0.34844629  0.007862887 0.6890297 0.05588076  0.3320744
2     IFNg  0.22658932 -0.019355272 0.4725339 0.08301859  0.3320744
3    IL-1b  0.38236003 -0.129061325 0.8937814 0.14587112  0.3889897
4    IL-1a  0.07009258 -0.482780169 0.6229653 0.80579133  0.8057913
5     IL-6 -0.06907883 -0.480417331 0.3422597 0.74478406  0.8057913
6      MIG  0.18998804 -0.391285224 0.7712613 0.52760464  0.8057913
7    IP-10 -0.20339690 -0.687108875 0.2803151 0.41175944  0.8057913
8   MIP-3a -0.07795639 -0.394900036 0.2389873 0.63077300  0.8057913
\end{verbatim}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Regression Table}\label{regression-table}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ============================================================================}
\CommentTok{\# Create a regression table using tbl\_regression() for the first cytokine}
\CommentTok{\# as a representative model, then build a combined table showing PCOS}
\CommentTok{\# coefficients across all cytokines}
\CommentTok{\# ============================================================================}

\CommentTok{\# Fit a model on the complete dataset (all cytokines) to show as a single}
\CommentTok{\# regression table using the first cytokine as a detailed example}
\NormalTok{first\_cyt }\OtherTok{\textless{}{-}}\NormalTok{ cytokines[}\DecValTok{1}\NormalTok{]}
\NormalTok{sub\_data\_first }\OtherTok{\textless{}{-}}\NormalTok{ analysis\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(cytokine }\SpecialCharTok{==}\NormalTok{ first\_cyt) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{pcos\_status =} \FunctionTok{factor}\NormalTok{(pcos\_status, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"no disease"}\NormalTok{, }\StringTok{"pcos"}\NormalTok{)),}
    \AttributeTok{time\_point =} \FunctionTok{factor}\NormalTok{(time\_point, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"week\_prior"}\NormalTok{, }\StringTok{"onset"}\NormalTok{,}
                                                \StringTok{"end\_bleeding"}\NormalTok{, }\StringTok{"week\_post"}\NormalTok{))}
\NormalTok{  )}

\NormalTok{fit\_first }\OtherTok{\textless{}{-}} \FunctionTok{lmer}\NormalTok{(log\_conc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pcos\_status }\SpecialCharTok{+}\NormalTok{ time\_point }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ pid),}
                  \AttributeTok{data =}\NormalTok{ sub\_data\_first)}

\CommentTok{\# Create regression table with tbl\_regression}
\NormalTok{reg\_table }\OtherTok{\textless{}{-}}\NormalTok{ fit\_first }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{tbl\_regression}\NormalTok{(}
    \AttributeTok{label =} \FunctionTok{list}\NormalTok{(}
\NormalTok{      pcos\_status }\SpecialCharTok{\textasciitilde{}} \StringTok{"PCOS status"}\NormalTok{,}
\NormalTok{      time\_point }\SpecialCharTok{\textasciitilde{}} \StringTok{"Time point"}
\NormalTok{    ),}
    \AttributeTok{estimate\_fun =} \SpecialCharTok{\textasciitilde{}} \FunctionTok{style\_number}\NormalTok{(.x, }\AttributeTok{digits =} \DecValTok{3}\NormalTok{),}
    \AttributeTok{pvalue\_fun =} \SpecialCharTok{\textasciitilde{}} \FunctionTok{style\_pvalue}\NormalTok{(.x, }\AttributeTok{digits =} \DecValTok{3}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{add\_global\_p}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{bold\_p}\NormalTok{()}

\CommentTok{\# Display}
\NormalTok{reg\_table}
\end{Highlighting}
\end{Shaded}

\begin{table}
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lccc}
\toprule
\textbf{Characteristic} & \textbf{Beta} & \textbf{95\% CI} & \textbf{p-value} \\ 
\midrule\addlinespace[2.5pt]
PCOS status &  &  & 0.804 \\ 
    no disease & — & — &  \\ 
    pcos & 0.070 & -0.511, 0.651 &  \\ 
Time point &  &  & {\bfseries <0.001} \\ 
    week\_prior & — & — &  \\ 
    onset & 2.158 & 1.549, 2.768 &  \\ 
    end\_bleeding & 1.907 & 1.298, 2.516 &  \\ 
    week\_post & 0.249 & -0.360, 0.859 &  \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\vspace{.05em}
Abbreviation: CI = Confidence Interval\\
\end{minipage}
\end{table}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Export as Word document}
\NormalTok{reg\_table }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{as\_flex\_table}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{save\_as\_docx}\NormalTok{(}\AttributeTok{path =} \StringTok{"Model\_Table\_PCOS.docx"}\NormalTok{)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Regression table saved to Model\_Table\_PCOS.docx}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Regression table saved to Model_Table_PCOS.docx
\end{verbatim}

\subsubsection{Cross-Cytokine PCOS Coefficient
Summary}\label{cross-cytokine-pcos-coefficient-summary}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ============================================================================}
\CommentTok{\# Build a combined table showing the PCOS coefficient for each cytokine}
\CommentTok{\# ============================================================================}

\CommentTok{\# Create a flextable from model results for reporting}
\NormalTok{cross\_table }\OtherTok{\textless{}{-}}\NormalTok{ model\_results }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \FunctionTok{across}\NormalTok{(}\FunctionTok{c}\NormalTok{(estimate, std\_error, ci\_lower, ci\_upper), }\SpecialCharTok{\textasciitilde{}} \FunctionTok{round}\NormalTok{(.x, }\DecValTok{3}\NormalTok{)),}
    \FunctionTok{across}\NormalTok{(}\FunctionTok{c}\NormalTok{(p\_value, p\_adjusted), }\SpecialCharTok{\textasciitilde{}} \FunctionTok{round}\NormalTok{(.x, }\DecValTok{4}\NormalTok{)),}
    \AttributeTok{significant =} \FunctionTok{ifelse}\NormalTok{(p\_adjusted }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{, }\StringTok{"Yes"}\NormalTok{, }\StringTok{"No"}\NormalTok{),}
    \AttributeTok{ci =} \FunctionTok{paste0}\NormalTok{(}\StringTok{"("}\NormalTok{, ci\_lower, }\StringTok{", "}\NormalTok{, ci\_upper, }\StringTok{")"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(cytokine, estimate, std\_error, ci, p\_value, p\_adjusted, significant) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{flextable}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{set\_header\_labels}\NormalTok{(}
    \AttributeTok{cytokine =} \StringTok{"Cytokine"}\NormalTok{,}
    \AttributeTok{estimate =} \StringTok{"Estimate"}\NormalTok{,}
    \AttributeTok{std\_error =} \StringTok{"SE"}\NormalTok{,}
    \AttributeTok{ci =} \StringTok{"95\% CI"}\NormalTok{,}
    \AttributeTok{p\_value =} \StringTok{"p{-}value"}\NormalTok{,}
    \AttributeTok{p\_adjusted =} \StringTok{"BH{-}adjusted p"}\NormalTok{,}
    \AttributeTok{significant =} \StringTok{"Significant"}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{theme\_booktabs}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{autofit}\NormalTok{()}

\NormalTok{cross\_table}
\end{Highlighting}
\end{Shaded}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable*}[c]{|p{0.88in}|p{0.88in}|p{0.67in}|p{1.29in}|p{0.79in}|p{1.25in}|p{0.99in}}



\ascline{1.5pt}{666666}{1-7}

\multicolumn{1}{>{\raggedright}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} Cytokine}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} Estimate}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.67in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} SE}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.29in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 95\%\ CI}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.79in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} p-value}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.25in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} BH-adjusted\ p}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.99in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} Significant}}}} \\

\ascline{1.5pt}{666666}{1-7}\endfirsthead 

\ascline{1.5pt}{666666}{1-7}

\multicolumn{1}{>{\raggedright}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} Cytokine}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} Estimate}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.67in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} SE}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.29in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 95\%\ CI}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.79in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} p-value}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.25in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} BH-adjusted\ p}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.99in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} Significant}}}} \\

\ascline{1.5pt}{666666}{1-7}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} TNFa}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.348}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.67in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.174}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.29in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} (0.008,\ 0.689)}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.79in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.0559}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.25in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.3321}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.99in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} No}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} IFNg}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.227}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.67in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.125}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.29in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} (-0.019,\ 0.473)}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.79in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.0830}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.25in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.3321}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.99in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} No}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} IL-1b}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.382}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.67in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.261}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.29in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} (-0.129,\ 0.894)}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.79in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.1459}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.25in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.3890}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.99in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} No}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} IL-1a}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.070}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.67in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.282}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.29in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} (-0.483,\ 0.623)}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.79in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.8058}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.25in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.8058}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.99in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} No}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} IL-6}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} -0.069}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.67in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.210}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.29in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} (-0.48,\ 0.342)}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.79in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.7448}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.25in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.8058}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.99in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} No}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} MIG}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.190}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.67in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.297}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.29in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} (-0.391,\ 0.771)}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.79in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.5276}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.25in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.8058}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.99in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} No}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} IP-10}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} -0.203}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.67in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.247}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.29in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} (-0.687,\ 0.28)}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.79in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.4118}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.25in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.8058}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.99in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} No}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} MIP-3a}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.88in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} -0.078}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.67in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.162}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.29in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} (-0.395,\ 0.239)}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.79in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.6308}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.25in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} 0.8058}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.99in+0\tabcolsep}}{\advance\leftskip by 5.0pt\relax \advance\rightskip by 5.0pt\relax \textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{{\fontspec{DejaVu Sans} No}}}} \\

\ascline{1.5pt}{666666}{1-7}



\end{longtable*}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Results Interpretation}\label{results-interpretation}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ============================================================================}
\CommentTok{\# Automatically generate interpretation based on model results}
\CommentTok{\# ============================================================================}

\NormalTok{n\_participants }\OtherTok{\textless{}{-}} \FunctionTok{n\_distinct}\NormalTok{(analysis\_data}\SpecialCharTok{$}\NormalTok{pid)}
\NormalTok{n\_pcos }\OtherTok{\textless{}{-}} \FunctionTok{n\_distinct}\NormalTok{(analysis\_data}\SpecialCharTok{$}\NormalTok{pid[analysis\_data}\SpecialCharTok{$}\NormalTok{pcos\_status }\SpecialCharTok{==} \StringTok{"pcos"}\NormalTok{])}
\NormalTok{n\_nodisease }\OtherTok{\textless{}{-}} \FunctionTok{n\_distinct}\NormalTok{(analysis\_data}\SpecialCharTok{$}\NormalTok{pid[analysis\_data}\SpecialCharTok{$}\NormalTok{pcos\_status }\SpecialCharTok{==} \StringTok{"no disease"}\NormalTok{])}
\NormalTok{n\_samples\_total }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(analysis\_data) }\SpecialCharTok{/} \FunctionTok{length}\NormalTok{(cytokines)  }\CommentTok{\# per cytokine}
\NormalTok{n\_cytokines }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(cytokines)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"============================================================}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
============================================================
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"             SESSION 2 INTERPRETATION}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
             SESSION 2 INTERPRETATION
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"============================================================}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
============================================================
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Research Question:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Research Question:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Do inflammatory marker levels differ between participants with PCOS}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Do inflammatory marker levels differ between participants with PCOS
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"and participants without PCOS after accounting for menstrual{-}cycle stage?}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
and participants without PCOS after accounting for menstrual-cycle stage?
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Sample Sizes:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Sample Sizes:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Total participants:"}\NormalTok{, n\_participants, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  Total participants: 27 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"    PCOS:"}\NormalTok{, n\_pcos, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
    PCOS: 14 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"    No disease:"}\NormalTok{, n\_nodisease, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
    No disease: 13 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Total samples per cytokine:"}\NormalTok{, n\_samples\_total, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  Total samples per cytokine: 108 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Cytokines analyzed:"}\NormalTok{, n\_cytokines, }\StringTok{"}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  Cytokines analyzed: 8 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Key Findings:}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Key Findings:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sig\_cytokines }\OtherTok{\textless{}{-}}\NormalTok{ model\_results }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(p\_adjusted }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{)}

\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{nrow}\NormalTok{(sig\_cytokines) }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"After fitting a linear mixed{-}effects model (log\_conc \textasciitilde{} pcos\_status + time\_point + (1|pid))}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"with Benjamini{-}Hochberg correction for multiple testing across"}\NormalTok{, n\_cytokines, }\StringTok{"cytokines,}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"none of the inflammatory markers showed a statistically significant difference}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"between PCOS and non{-}PCOS participants at the adjusted significance threshold (alpha = 0.05).}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}

  \CommentTok{\# Show the closest to significance}
\NormalTok{  top\_cyt }\OtherTok{\textless{}{-}}\NormalTok{ model\_results }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{slice\_min}\NormalTok{(p\_adjusted, }\AttributeTok{n =} \DecValTok{1}\NormalTok{)}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"The cytokine closest to significance was"}\NormalTok{, top\_cyt}\SpecialCharTok{$}\NormalTok{cytokine[}\DecValTok{1}\NormalTok{],}
      \StringTok{"(BH{-}adjusted p ="}\NormalTok{, }\FunctionTok{round}\NormalTok{(top\_cyt}\SpecialCharTok{$}\NormalTok{p\_adjusted[}\DecValTok{1}\NormalTok{], }\DecValTok{4}\NormalTok{), }\StringTok{").}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"After fitting linear mixed{-}effects models (log\_conc \textasciitilde{} pcos\_status + time\_point + (1|pid))}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"with Benjamini{-}Hochberg correction for multiple testing, the following cytokine(s)}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"showed statistically significant differences between PCOS and non{-}PCOS participants:}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}

  \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \FunctionTok{seq\_len}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(sig\_cytokines))) \{}
\NormalTok{    cyt }\OtherTok{\textless{}{-}}\NormalTok{ sig\_cytokines}\SpecialCharTok{$}\NormalTok{cytokine[i]}
\NormalTok{    est }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(sig\_cytokines}\SpecialCharTok{$}\NormalTok{estimate[i], }\DecValTok{3}\NormalTok{)}
\NormalTok{    ci\_l }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(sig\_cytokines}\SpecialCharTok{$}\NormalTok{ci\_lower[i], }\DecValTok{3}\NormalTok{)}
\NormalTok{    ci\_u }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(sig\_cytokines}\SpecialCharTok{$}\NormalTok{ci\_upper[i], }\DecValTok{3}\NormalTok{)}
\NormalTok{    p\_adj }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(sig\_cytokines}\SpecialCharTok{$}\NormalTok{p\_adjusted[i], }\DecValTok{4}\NormalTok{)}
\NormalTok{    direction }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(est }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, }\StringTok{"higher"}\NormalTok{, }\StringTok{"lower"}\NormalTok{)}

    \FunctionTok{cat}\NormalTok{(}\StringTok{"  {-}"}\NormalTok{, cyt, }\StringTok{": estimate ="}\NormalTok{, est, }\StringTok{"("}\NormalTok{, ci\_l, }\StringTok{","}\NormalTok{, ci\_u, }\StringTok{"),}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"    BH{-}adjusted p ="}\NormalTok{, p\_adj, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"    Interpretation:"}\NormalTok{, cyt, }\StringTok{"levels were"}\NormalTok{, direction, }\StringTok{"in PCOS participants}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"    compared to non{-}PCOS participants after adjusting for menstrual{-}cycle stage.}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{  \}}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
After fitting a linear mixed-effects model (log_conc ~ pcos_status + time_point + (1|pid))
with Benjamini-Hochberg correction for multiple testing across 8 cytokines,
none of the inflammatory markers showed a statistically significant difference
between PCOS and non-PCOS participants at the adjusted significance threshold (alpha = 0.05).

The cytokine closest to significance was TNFa (BH-adjusted p = 0.3321 ).
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Statistical Methods:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Statistical Methods:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  {-} Linear mixed{-}effects models with random intercepts per participant}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  - Linear mixed-effects models with random intercepts per participant
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  {-} Fixed effects: PCOS status (primary predictor), time point (adjustment)}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  - Fixed effects: PCOS status (primary predictor), time point (adjustment)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  {-} Multiple testing correction: Benjamini{-}Hochberg (BH) procedure}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  - Multiple testing correction: Benjamini-Hochberg (BH) procedure
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  {-} Log transformation: log1p (log(1 + concentration))}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  - Log transformation: log1p (log(1 + concentration))
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Important Caveat:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Important Caveat:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  This is an exploratory analysis. The relatively small sample size limits}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  This is an exploratory analysis. The relatively small sample size limits
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  statistical power. Results should be interpreted cautiously and validated}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  statistical power. Results should be interpreted cautiously and validated
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  in larger, independent cohorts.}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  in larger, independent cohorts.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"============================================================}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
============================================================
\end{verbatim}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Session Information}\label{session-information}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sessionInfo}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
R version 4.5.3 (2026-03-11)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 24.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.26.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] knitr_1.51       officer_0.7.5    flextable_0.9.12 lmerTest_3.2-1  
 [5] lme4_2.0-1       Matrix_1.7-4     ggpubr_0.6.3     gtsummary_2.5.1 
 [9] lubridate_1.9.5  forcats_1.0.1    stringr_1.6.0    dplyr_1.2.0     
[13] purrr_1.2.1      readr_2.2.0      tidyr_1.3.2      tibble_3.3.1    
[17] ggplot2_4.0.2    tidyverse_2.0.0 

loaded via a namespace (and not attached):
  [1] Rdpack_2.6.6            rlang_1.1.7             magrittr_2.0.4         
  [4] furrr_0.4.0             otel_0.2.0              compiler_4.5.3         
  [7] systemfonts_1.3.2       vctrs_0.7.1             pkgconfig_2.0.3        
 [10] crayon_1.5.3            fastmap_1.2.0           backports_1.5.0        
 [13] labeling_0.4.3          rmarkdown_2.30          markdown_2.0           
 [16] tzdb_0.5.0              haven_2.5.5             nloptr_2.2.1           
 [19] ragg_1.5.1              bit_4.6.0               xfun_0.56              
 [22] labelled_2.16.0         cachem_1.1.0            litedown_0.9           
 [25] jsonlite_2.0.0          uuid_1.2-2              broom_1.0.12           
 [28] parallel_4.5.3          R6_2.6.1                bslib_0.10.0           
 [31] stringi_1.8.7           RColorBrewer_1.1-3      parallelly_1.47.0      
 [34] car_3.1-5               boot_1.3-32             estimability_1.5.1     
 [37] jquerylib_0.1.4         numDeriv_2016.8-1.1     Rcpp_1.1.1             
 [40] parameters_0.29.1       splines_4.5.3           timechange_0.4.0       
 [43] tidyselect_1.2.1        abind_1.4-8             yaml_2.3.12            
 [46] codetools_0.2-20        listenv_0.10.1          lattice_0.22-9         
 [49] bayestestR_0.18.1       withr_3.0.2             S7_0.2.1               
 [52] askpass_1.2.1           coda_0.19-4.1           evaluate_1.0.5         
 [55] future_1.70.0           zip_2.3.3               xml2_1.5.2             
 [58] pillar_1.11.1           carData_3.0-6           insight_1.5.1          
 [61] reformulas_0.4.4        generics_0.1.4          vroom_1.7.0            
 [64] hms_1.1.4               commonmark_2.0.0        scales_1.4.0           
 [67] minqa_1.2.8             xtable_1.8-8            globals_0.19.1         
 [70] glue_1.8.0              gdtools_0.5.1           emmeans_2.0.3          
 [73] tools_4.5.3             data.table_1.18.2.1     ggsignif_0.6.4         
 [76] mvtnorm_1.4-0           fs_1.6.7                grid_4.5.3             
 [79] rbibutils_2.4.1         datawizard_1.3.1        cards_0.8.0            
 [82] nlme_3.1-168            patchwork_1.3.2         cardx_0.3.3            
 [85] Formula_1.2-5           cli_3.6.5               textshaping_1.0.5      
 [88] fontBitstreamVera_0.1.1 broom.helpers_1.22.0    gt_1.3.0               
 [91] gtable_0.3.6            broom.mixed_0.2.9.7     rstatix_0.7.3          
 [94] sass_0.4.10             digest_0.6.39           fontquiver_0.2.1       
 [97] farver_2.1.2            htmltools_0.5.9         lifecycle_1.0.5        
[100] fontLiberation_0.1.0    openssl_2.3.5           bit64_4.6.0-1          
[103] MASS_7.3-65            
\end{verbatim}




\end{document}
